name: cron-page-revalidation

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # (see https://crontab.guru)
    - cron: "0 * * * *"
jobs:
  remoteok:
    env:
      APP_URL: ${{ secrets.APP_URL }}
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl '${{ secrets.APP_URL }}/api/revalidate?secret=${{ secrets.SECRET_TOKEN }}'
